"""add session claim_status

Revision ID: 25cd0a46c495
Revises: c40881a681f2
Create Date: 2026-07-18 02:56:47.451947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cd0a46c495'
down_revision: Union[str, Sequence[str], None] = 'c40881a681f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('claim_status', sa.Enum('pending', 'approved', name='sessionclaimstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'claim_status')
    # ### end Alembic commands ###
