"""session presenter and topic nullable

Revision ID: 30d2ccef413d
Revises: abb9d580a7d4
Create Date: 2026-07-17 08:40:20.602084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30d2ccef413d'
down_revision: Union[str, Sequence[str], None] = 'abb9d580a7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'presenter_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'topic',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'topic',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('sessions', 'presenter_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
