"""add application discord_id

Revision ID: 37067d11f048
Revises: de4709938a2d
Create Date: 2026-07-18 11:45:17.055030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37067d11f048'
down_revision: Union[str, Sequence[str], None] = 'de4709938a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('discord_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'discord_id')
    # ### end Alembic commands ###
