"""add session discord_event_id

Revision ID: 56430073f3ad
Revises: 30d2ccef413d
Create Date: 2026-07-17 10:44:01.029809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56430073f3ad'
down_revision: Union[str, Sequence[str], None] = '30d2ccef413d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('discord_event_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'discord_event_id')
    # ### end Alembic commands ###
