"""add discord and presentation settings to study_settings

Revision ID: 6eaf7294f2b4
Revises: 56430073f3ad
Create Date: 2026-07-17 11:36:56.013883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eaf7294f2b4'
down_revision: Union[str, Sequence[str], None] = '56430073f3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_settings', sa.Column('discord_guild_id', sa.String(length=64), nullable=True))
    op.add_column('study_settings', sa.Column('discord_voice_channel_id', sa.String(length=64), nullable=True))
    op.add_column('study_settings', sa.Column('presentation_time', sa.String(length=5), nullable=True))
    op.add_column('study_settings', sa.Column('presentation_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_settings', 'presentation_duration_minutes')
    op.drop_column('study_settings', 'presentation_time')
    op.drop_column('study_settings', 'discord_voice_channel_id')
    op.drop_column('study_settings', 'discord_guild_id')
    # ### end Alembic commands ###
