"""add application discord_joined

Revision ID: 94de5a67d429
Revises: 44d5f842a78a
Create Date: 2026-07-20 03:42:21.386869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94de5a67d429'
down_revision: Union[str, Sequence[str], None] = '44d5f842a78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'applications',
        sa.Column('discord_joined', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'discord_joined')
    # ### end Alembic commands ###
