"""add calendar event discord fields

Revision ID: de4709938a2d
Revises: 25cd0a46c495
Create Date: 2026-07-18 03:13:58.003022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4709938a2d'
down_revision: Union[str, Sequence[str], None] = '25cd0a46c495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('event_time', sa.String(length=5), nullable=True))
    op.add_column('calendar_events', sa.Column('discord_event_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'discord_event_id')
    op.drop_column('calendar_events', 'event_time')
    # ### end Alembic commands ###
